### ISSUE TITLE
깃 + 코딩컨벤션

### ISSUE THREAD

**Issue by 2897robo** [nhnacademy-be6-5ritang/NHN_BookStore#127]
* 깃사용법 주의사항
https://velog.io/@shin6403/Git-git-%EC%BB%A4%EB%B0%8B-%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0

* 코딩컨벤션 규칙 정하기
https://bestinu.tistory.com/64

**Comment by dlrudgjs104** [comment]
- global 패키지에서 exception 공통 처리
- 네이버 코딩 컨벤션 사용
- DTO 타입 record 형식 지향
- 데이터베이스 데시멀 타입은 자바에서 빅데시멀로 사용
- 엔티티 파일이름은 단수형 @Table 매핑은 복수형으로 cf) Order.class, @Table(name = "orders")
- @Setter 사용 지양
- 서비스 레이어 @Transactional사용, get은 @Transactional(readOnly = true)사용
